apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  containers:
    - image: busybox
      name: my-frontend
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: my-do-volume
          mountPath: "/data"
  volumes:
    - name: my-do-volume
      persistentVolumeClaim:
        claimName: kplabs-pvc
