apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc
spec:
  containers:
    - image: nginx
      name: pod-pvc
      volumeMounts:
        - name: my-volume
          mountPath: "/data"
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: pvc
