apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-volume
  name: pod-volume
spec:
  containers:
    - image: nginx
      name: pod-volume
      volumeMounts:
        - name: first-volume
          mountPath: /data
  volumes:
    - name: first-volume
      hostPath:
        path: /mydata
        type: Directory
