apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
  - name: test-container
    image: nginx
    volumeMounts:
    - mountPath: /etc/config
      name: config-volume
  volumes:
  -  name: config-volume
     configMap:
       name: dev-properties
  restartPolicy: Never