apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kplabs-quota
  name: kplabs-quota
spec:
  containers:
  - image: nginx
    name: kplabs-quota
    resources:
      requests:
        memory: "128Mi"
        cpu: "0.00001"
      limits:
        cpu: "2"
        memory: "512Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}