# kubectl create secret generic kplabs-secret --from-literal=user=admin --from-literal=pass=12345
apiVersion: v1
data:
  pass: MTIzNDU=
  user: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: null
  name: kplabs-secret

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-env
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: kplabs-secret
          key: user
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: kplabs-secret
          key: pass 

