apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kplabs-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          activeDeadlineSeconds: 10
          containers:
          - name: hello
            image: busybox
            imagePullPolicy: IfNotPresent
            command: ["curl",  "kplabs.in/ping"]
          restartPolicy: OnFailure
