apiVersion: apps/v1
kind: Deployment
metadata:
  name: kplabs-selector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
      nodeSelector:
        disktype: ssd

# kubectl label node pool-hrhwxjzi6-kcru disktype=ssd