apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kplabs-configuration
  name: kplabs-configuration
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kplabs-configuration
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kplabs-configuration
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}


# kubectl edit deployment kplabs-configuration
# kubectl set image deployment kplabs-configuration kplabs-configuration=nginx:alpine --record