apiVersion: v1
kind: Pod
metadata:
  name: busybox-security
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
    fsGroup: 3000
  containers:
  - name: busybox-container
    image: busybox
    command: ["sleep", "3600" ]