apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: configmap-pod
  name: configmap-pod
spec:
  containers:
  - image: nginx
    name: configmap-pod
    resources: {}
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: kplabs-config
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}