apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kplabs-pv-pod
  name: kplabs-pv-pod
spec:
  containers:
  - image: nginx
    name: kplabs-pv-pod
    resources: {}
    volumeMounts:
    - name: myvolume
      path: /mydata
  volumes:
  - name: myvolume
    persistentVolumeClaim:
      claimName: kplabs-pvc
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}