apiVersion: v1
kind: Pod
metadata:
  name: demopod-volume
spec:
  containers:
  - name: test-container
    image: nginx
    volumeMounts:
    - mountPath: /data
      name: first-volume
  volumes:
  -  name: first-volume
     hostPath:
       path: /mydata
       type: Directory