apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: service-pod
  name: service-pod
spec:
  containers:
  - image: nginx
    name: service-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
    disk: ssd
status: {}