apiVersion: v1
kind: Pod
metadata:
  name: kplabs-pod-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: NotIn
              values:
              - frontend
          topologyKey: topology.kubernetes.io/hostname            
  containers:
  - name: pod-affinity
    image: nginx