apiVersion: v1
kind: Pod
metadata:
  name: newprobe
spec:
  containers:
  - name: nginx
    image: nginx
    command:
    - /bin/sh
    - -c
    - touch /tmp/myfile; 3600
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/myfile
      initialDelaySeconds: 5
      periodSeconds: 5