kind: Pod
apiVersion: v1
metadata:
  name: secretpod-env
spec:
  containers:
  - name: secretpod-env
    image: nginx
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: firstsecret
          key: dbpass
  restartPolicy: Never