apiVersion: v1
kind: Secret
metadata:
  name: thirdsecret
type: Opaque
data:
  username: ZGJhZG1pbg==
  password: bXlwYXNzd29yZDEyMw==

# Base64 encode in unix
# echon -n 'dbadmin' | base64
# echon -n 'mypassword123' | base64
