apiVersion: v1
kind: Pod
metadata:
  name: secret-env
spec:
  containers:
    - image: nginx
      name: secret-env
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: firstsecret
              key: dbpass
